//instance_ami="m-j6cj2liju58d88zmgbdg"  //or auto
product_intl= "^Fortinet FortiGate .*\\(8 vCPUs.*.+7.0.+2"
product_china="^Fortinet FortiGate-6.4.5"
account_region="intl" //or china
license_type="pygo" //or byol
region="cn-hongkong"
//license1="./FGVMULTM22000730.lic"
//license2="./FGVMULTM22000750.lic"
license1="./nolicense.lic"
license2="./nolicense.lic"
