apiVersion: v1
kind: Pod
metadata:
  name: helloworld2
spec:
  containers:
  - name: helloworld2
    image: busybox
    command: [ "sleep","3600" ] 
    volumeMounts: 
    - mountPath: /test-data
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /data
      type: DirectoryOrCreate
