--- 

kind: Namespace
apiVersion: v1
metadata:
  name: jenkins
  labels:
    name: jenkins

---

apiVersion: v1
kind: ServiceAccount
metadata:
 name: jenkins-account
 namespace: jenkins

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: jenkins-master
  namespace: jenkins
  labels:
    app: jenkins-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-master
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      serviceAccountName: jenkins-account
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: jenkins
        image: interbeing/jenkinswithdockerclient:latest
        env: 
        - name: DOCKER_HOST
          value: "tcp://10.1.1.172:2375"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 50000
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
      volumes:
      - name: jenkins-home
        emptyDir: {}

---

kind: Service
apiVersion: v1
metadata:
  name: jenkins-ui
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins-master
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100
      name: ui

---

kind: Service
apiVersion: v1
metadata:
  name: jenkins-discovery
  namespace: jenkins
spec:
  selector:
    app: jenkins-master
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
      name: agents

---

apiVersion: v1
kind: Service
metadata:
  name: nlb-jenkins-ui
  namespace: jenkins
spec:
  ports:
    - protocol: TCP
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: jenkins-master
  type: LoadBalancer
