apiVersion: v1
kind: Service
metadata:
  name: nlb-jenkins-ui
  namespace: jenkins
spec:
  ports:
    - protocol: TCP
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: jenkins-master
  type: LoadBalancer
